// <auto-generated />
namespace mcknaldi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changebezorgadres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changebezorgadres));
        
        string IMigrationMetadata.Id
        {
            get { return "201807121916235_change-bezorgadres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
